### ISSUE TITLE
LICENSE for repository

### ISSUE THREAD

**Issue by alexggmatthews** [noegroup/stochastic_normalizing_flows#2]
Thanks for open sourcing this code. I would be interested in trying it out at DeepMind, but it makes it difficult unless the license is specified in the repository. If that is something you are able to do, it is most straightforward if you put in a LICENSE file. I can try if it has for instance Apache 2.0 or MIT though of course I can't advise you what license works best in your case. At DeepMind we use Apache 2.0. Happy to discuss further. Thanks very much,
Alex

**Comment by jonkhler** [comment]
Added LICENSE to the repo

**Comment by alexggmatthews** [comment]
Thank you.
